TebLocalPlannerROS:

 odom_topic: odom
 map_frame: map 
    
 # Trajectory
  
 teb_autosize: True
 dt_ref: 0.3
 dt_hysteresis: 0.1 
 global_plan_overwrite_orientation: True
 max_global_plan_lookahead_dist: 2.0 # Aumentato per una maggiore visualizzazione del percorso
 feasibility_check_no_poses: 5

 publish_feedback: true
    
 # Robot

 max_vel_x: 0.8 # Aumentato per una maggiore velocità
 max_vel_x_backwards: 0.4
 max_vel_theta: 1.0 # Aumentato per una maggiore velocità di rotazione
 acc_lim_x: 1.0 # Aumentato per una maggiore accelerazione lineare
 acc_lim_theta: 1.5  # Aumentato per una maggiore accelerazione angolare
 min_turning_radius: 0.0
 footprint_model: 
  type: "circular"
  radius: 0.12
          
 # GoalTolerance

 xy_goal_tolerance: 0.2 # Tolleranza sulla posizione finale del goal
 yaw_goal_tolerance: 0.2  # Tolleranza sull'orientamento finale del goal
 free_goal_vel: False
    
 # Obstacles
    
 min_obstacle_dist: 0.2 # Ridotto per una maggiore vicinanza agli ostacoli
 include_costmap_obstacles: True
 costmap_obstacles_behind_robot_dist: 1.0
 obstacle_poses_affected: 20 
 costmap_converter_plugin: "" 
 costmap_converter_spin_thread: True
 costmap_converter_rate: 5 # Aumentato per una maggiore frequenza di aggiornamento del costmap
 inflation_dist: 0.1
 include_dynamic_obstacles: false

 # Optimization
    
 no_inner_iterations: 3 
 no_outer_iterations: 2 
 optimization_activate: True
 optimization_verbose: false
 penalty_epsilon: 0.05
 weight_max_vel_x: 1.5
 weight_max_vel_theta: 0.8
 weight_acc_lim_x: 0.8
 weight_acc_lim_theta: 1.0
 weight_kinematics_nh: 800.0
 weight_kinematics_forward_drive: 150.0 
 weight_kinematics_turning_radius: 5.0
 weight_optimaltime: 1.0
 weight_obstacle: 150.0 
 weight_dynamic_obstacle: 15.0
 selection_alternative_time_cost: False 

 # Homotopy Class Planner

 enable_homotopy_class_planning: False 
 enable_multithreading: True
 simple_exploration: False
 max_number_classes: 4 
 roadmap_graph_no_samples: 15
 roadmap_graph_area_width: 5
 h_signature_prescaler: 0.5
 h_signature_threshold: 0.1